version: '3'

services:

  test:
#    build: ./test/
    image: kurz:dev
    command: go test -v -p 1 -timeout=60s ./test/integration_test.go
#    environment:
#      - REDIS_URL=redis://redis
#    depends_on:
#      - redis

#  redis:
#    image: redis/redis:latest