name: build
on: [push, pull_request]
jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - name: Run linter
        uses: golangci/golangci-lint-action@v3

#  unit:
#    name: Unit Tests
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 1
#      - name: Setup Go
#        uses: actions/setup-go@v3
#        with:
#          go-version: 1.20
#      - name: Install dependencies
#        run: go mod download
#      - name: Run unit tests
#        run: make test