name: build
on: [push, pull_request]
jobs:

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version: [1.20]
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install linter
        run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.18.0
      - name: Run linter
        run: ./bin/golangci-lint run

  unit:
    name: Unit Tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version: [1.20]
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go mod download
      - name: Run unit tests
        run: make test